CREATE TABLE IF NOT EXISTS users (
  userId INTEGER PRIMARY KEY AUTOINCREMENT, 
  email VARCHAR(30) NOT NULL, 
  pass VARCHAR(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS medicine (
  medicineId INTEGER PRIMARY KEY AUTOINCREMENT, 
  userId INTEGER NOT NULL, 
  count INTEGER, 
  drinkTime TIME, 
  date DATE, 
  FOREIGN KEY(userId) REFERENCES users(userId)
);

CREATE TABLE IF NOT EXISTS mood (
  moodId INTEGER PRIMARY KEY AUTOINCREMENT, 
  userId INTEGER NOT NULL, 
  mood INTEGER, 
  date DATE, 
  FOREIGN KEY(userId) REFERENCES users(userId)
);